### ISSUE TITLE
v0.2.12

### ISSUE THREAD

**Issue by rossdotparker** [raynichc/Trip-Planner#18]
Hi Ray, I've added a new feature to Trip Planner, and wrapped it up as v0.2.12. I was hoping to offer it to you as a PR, but I don't have permissions on your repo. So, it is attached here. Any chance you can roll this into your official version and do a release? Don't want to lose the feature next time we upgrade. Thanks!
[Trip-Planner.zip](https://github.com/raynichc/Trip-Planner/files/2309209/Trip-Planner.zip)

**Comment by raynichc** [comment]
Committed and released a new version. Thanks for this. I think I've fixed the PR problem now.

**Comment by rossdotparker** [comment]
Thanks for this Ray : ) You should have a follow up from me, regarding v0.2.13, which has some further tweaks. Hopefully all OK to include in your master branch as a release, but let me know if there are any issues.
