### ISSUE TITLE
Access to Repo

### ISSUE THREAD

**Issue by rossdotparker** [raynichc/Trip-Planner#21]
Hi Ray, any chance I can get access to this repo so that I can push some changes for you to take a look at? Thanks!

**Comment by raynichc** [comment]
That's odd, I think you are one of the Collaborators.

**Comment by rossdotparker** [comment]
Excellent, thanks for sharing. I now have the same rights. I dropped you a couple message on Slack. Want to take a look and let me know if you have happy for me to push that new version, and what you want to do about the notifications suggestion? Thanks : )
